### ISSUE TITLE
shasum not existing

### ISSUE THREAD

**Issue by sebastiw** [keith/pre-commit-buildifier#17]
Hi,

I'm on `Linux Heimdallr 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux` and `shasum` does not seem to exist. As far as I can tell, it's a perl wrapper script the more specific sha-scripts `sha1sum`, `sha224sum`,  `sha256sum`,  `sha384sum`,  `sha512sum`. where sha1sum would be used by default?

Is it possible to change it to not use the wrapper and instead use the specific sha-script?

**Comment by keith** [comment]
fixed in https://github.com/keith/pre-commit-buildifier/releases/tag/6.1.0.2, thanks!
